apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-api
  namespace: api
  labels:
    name: dummy-api
    app: dummy-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-api
  template:
    metadata:
      labels:
        app: dummy-api
    spec:
      containers:
        - image: dummy-api
          name: dummy-api
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 1
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 1
            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-service
  namespace: api
spec:
  ports:
    - name: "default-http-port"
      port: 8080
      targetPort: 8080
  selector:
    app: dummy-api
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dummy-api-allow
  namespace: api
spec:
  podSelector:
    matchLabels:
      app: dummy-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: tmac-k8s-dev-dmz
        - podSelector:
            matchLabels:
              app: kong
      ports:
        - port: 8080
